### ISSUE TITLE
Add support for GitHub actions

### ISSUE THREAD

**Issue by jgangemi** [hazendaz/coveralls-maven-plugin#112]
Native support for GitHub actions is needed in order to send over the pull request number in order for commenting and status checks to work.

**Comment by LorenzoBettini** [comment]
Sorry if I go back to this issue, which seems to have been resolved.
I don't understand how this is meant to work.
How do I get support for GitHub Actions? I have a Java/Maven project covered by JaCoCo.
Should I pass `-DserviceName=github`?
Even if I do that, the URL to the corresponding "GITHUB ACTIONS RUN" is wrong. For example, it is something like `https://github.com/<...>/actions/runs/152`, which does not exist; indeed, the correct integer for the action is something much higher, e.g., 13055479157.

Does this automatic support also imply that the PR number is taken automatically without further specification?
Looking at here: https://github.com/hazendaz/coveralls-maven-plugin/blob/master/.github/workflows/coveralls.yaml#L19, it looks like the PR number must still be passed explicitly.

Does this support also imply that I can pass GITHUB_TOKEN (automatic secret) as `repoToken` instead of encoding the Coveralls repo token as an additional secret in my GitHub repository?

Thanks in advance

**Comment by jgangemi** [comment]
this is how i'm invoking the plugin as part of my build process. i have the repository token stored as a github secret.

https://github.com/dangernoodle-io/dangernoodle-io-build-pom/blob/main/pom.xml#L290

the plugin figures out it is running as part of a github action w/o any other configuration needed other then passing the coveralls repository token.

example pull request where coveralls is reporting back against the pull request: https://github.com/dangernoodle-io/central-publisher-webhook/pull/14

**Comment by jgangemi** [comment]
looking here: 

https://github.com/hazendaz/coveralls-maven-plugin/blob/master/src/main/java/org/eluder/coveralls/maven/plugin/service/GitHub.java#L67 

the `GITHUB_RUN_ID`, which according to the [docs](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/store-information-in-variables#default-environment-variables) is this
```
A unique number for each workflow run within a repository. This number does not change if you re-run the workflow run. For example, 1658821493
```
should be pointing back to the workflow run itself.

i'll see if i can find some time to investigate since i worked on this. if you are able grab a capture of the current set of default env variables being set by github, that would help move things along faster.

**Comment by LorenzoBettini** [comment]
@jgangemi I added further information in the new issue I opened, in particular, https://github.com/hazendaz/coveralls-maven-plugin/issues/154#issuecomment-2625160691
